// angular-guest/src/app/app.component.ts
import { Component, HostListener } from "@angular/core";

@Component({
  standalone: true,
  templateUrl: "./app.component.html",
})
export class AppComponent {
  value = 0;

  @HostListener("window:increment", ["$event.detail"])
  increment(newValue: number) {
    this.value = newValue;
  }
}

<div style="border: 1px solid red; margin: 16px; padding: 16px">
  <p>Angular Guest</p>
  <p>Value: {{ value }}</p>
</div>

// react-guest/src/app.tsx
import { useEffect, useState } from "react";

export function App() {
  const [value, setValue] = useState(0);

  useEffect(() => {
    const controller = new AbortController();
    const { signal } = controller;

    window.addEventListener(
      "increment",
      (event) => setValue((event as CustomEvent).detail),
      { signal }
    );

    return () => controller.abort();
  }, []);

  return (
    <div style={{ border: "1px solid blue", margin: "16px", padding: "16px" }}>
      <p>React Guest</p>
      <p>Value: {value}</p>
    </div>
  );
}
