// angular-guest/src/app/app.component.ts
import { Component, HostListener } from "@angular/core";

@Component({
  standalone: true,
  templateUrl: "./app.component.html",
})
export class AppComponent {
  value = -1;

  ngOnInit() {
    const event = new Event("What is the current value?");
    window.dispatchEvent(event);
  }

  @HostListener("window:Current value is", ["$event"])
  handleValue(event: CustomEvent) {
    this.value = event.detail;
  }
}

<div style="border: 1px solid red; margin: 16px; padding: 16px">
  <p>Angular Guest</p>
  <p>Value: {{ value }}</p>
</div>

// react-guest/src/App.tsx
import { useEffect, useState } from "react";

function App() {
  const [value, setValue] = useState(-1);

  useEffect(() => {
    const controller = new AbortController();
    const { signal } = controller;

    // listen for the response
    window.addEventListener("Current value is", handleValue, { signal });

    // ask
    const event = new Event("What is the current value?");
    window.dispatchEvent(event);

    return () => controller.abort();
  }, []);

  function handleValue(event: Event) {
    setValue((event as CustomEvent).detail);
  }

  return (
    <div style={{ border: "1px solid blue", margin: "16px", padding: "16px" }}>
      <p>React Guest</p>
      <p>Value: {value}</p>
    </div>
  );
}

export default App;
