// angular-guest/src/main.ts
import { createApplication } from "@angular/platform-browser";
import { AppComponent } from "./app/app.component";
import { createComponent, NgZone } from "@angular/core";

window.render_angular_guest = (rootId: string) => {
  window.unmount_angular_guest = undefined;
  createApplication().then((appRef) => {
    const root = document.getElementById(rootId);
    if (!root) {
      console.error(`Unable to find root with id: ${rootId}`);
      return;
    }
    const zone = appRef.injector.get(NgZone);
    zone.run(() => {
      const app = createComponent(AppComponent, {
        environmentInjector: appRef.injector,
        hostElement: root,
      });
      appRef.attachView(app.hostView);
    });
    window.unmount_angular_guest = () => appRef.destroy();
  });
};

// react-guest/src/main.tsx
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.tsx";

window.render_react_guest = (rootId: string) => {
  const root = document.getElementById(rootId);
  if (!root) {
    console.error(`Unable to find root with ID: ${rootId}`);
    return;
  }
  ReactDOM.createRoot(root).render(
    <React.StrictMode>
      <App />
    </React.StrictMode>
  );
};
